// <auto-generated />
using System;
using Anthology.Modules.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anthology.Modules.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260609121956_Catalog_PrefixExternalIds")]
    partial class Catalog_PrefixExternalIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anthology.Modules.Catalog.Title", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("MediaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("media_data");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<Guid?>("ParentTitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_title_id");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("TitleId")
                        .HasName("pk_titles");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_titles_external_id");

                    b.HasIndex("ParentTitleId", "SortOrder")
                        .HasDatabaseName("ix_titles_parent_title_id_sort_order");

                    b.ToTable("titles", "catalog");
                });

            modelBuilder.Entity("Anthology.Modules.Catalog.Title", b =>
                {
                    b.HasOne("Anthology.Modules.Catalog.Title", null)
                        .WithMany()
                        .HasForeignKey("ParentTitleId")
                        .HasConstraintName("fk_titles_titles_parent_title_id");
                });
#pragma warning restore 612, 618
        }
    }
}
