// <auto-generated />
using System;
using Anthology.Modules.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Anthology.Modules.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260611091540_Catalog_AddBackdropPath")]
    partial class Catalog_AddBackdropPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anthology.Modules.Catalog.Title", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text")
                        .HasColumnName("backdrop_path");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.PrimitiveCollection<string[]>("Genres")
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("MediaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("media_data");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<Guid?>("ParentTitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_title_id");

                    b.Property<double?>("Popularity")
                        .HasColumnType("double precision")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("vote_average");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("TitleId")
                        .HasName("pk_titles");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_titles_external_id");

                    b.HasIndex("Genres")
                        .HasDatabaseName("ix_titles_genres");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Genres"), "gin");

                    b.HasIndex("Keywords")
                        .HasDatabaseName("ix_titles_keywords");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Keywords"), "gin");

                    b.HasIndex("ParentTitleId", "SortOrder")
                        .HasDatabaseName("ix_titles_parent_title_id_sort_order");

                    b.ToTable("titles", "catalog");
                });

            modelBuilder.Entity("Anthology.Modules.Catalog.TitleCredit", b =>
                {
                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<string>("ExternalPersonId")
                        .HasColumnType("text")
                        .HasColumnName("external_person_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("TitleId", "ExternalPersonId", "Role")
                        .HasName("pk_title_credits");

                    b.HasIndex("ExternalPersonId")
                        .HasDatabaseName("ix_title_credits_external_person_id");

                    b.ToTable("title_credits", "catalog");
                });

            modelBuilder.Entity("Anthology.Modules.Catalog.Title", b =>
                {
                    b.HasOne("Anthology.Modules.Catalog.Title", null)
                        .WithMany()
                        .HasForeignKey("ParentTitleId")
                        .HasConstraintName("fk_titles_titles_parent_title_id");
                });
#pragma warning restore 612, 618
        }
    }
}
