// <auto-generated />
using System;
using Anthology.Modules.Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anthology.Modules.Tracking.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260605070405_Tracking_Initial")]
    partial class Tracking_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracking")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anthology.Modules.Tracking.DiaryEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("UserId", "TitleId", "OccurredAt")
                        .HasName("pk_diary_entries");

                    b.HasIndex("UserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_diary_entries_user_id_occurred_at");

                    b.ToTable("diary_entries", "tracking");
                });

            modelBuilder.Entity("Anthology.Modules.Tracking.LibraryItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("UserId", "TitleId")
                        .HasName("pk_library_items");

                    b.HasIndex("UserId", "AddedAt", "TitleId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_library_items_user_id_added_at_title_id");

                    b.HasIndex("UserId", "Rating", "TitleId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_library_items_user_id_rating_title_id");

                    b.ToTable("library_items", "tracking");
                });
#pragma warning restore 612, 618
        }
    }
}
